### ISSUE TITLE
Set libretro build platform explicitly for linux

### ISSUE THREAD

**Issue by fetzerch** [fetzerch/kodi-game-scripting#12]
Most cores check `uname -a` which includes the hostname. if *win* is included in that, it'll try to do a windows build.
Unfortunately `platform=unix` does not work with all cores. For bnes platform has to be set to `x`.

Options:
- Unify `platform=unix` upstream (depends on how many cores are affected)
- Allow to override it per core in config.py

See: https://github.com/kodi-game/game.libretro.2048/pull/3

**Comment by garbear** [comment]
I think we should upstream, because other build systems might want to avoid special-casing all these cores

**Comment by fetzerch** [comment]
Yeah makes sense, i just don't yet know how many are affected.

**Comment by fetzerch** [comment]
Fixed bnes [upstream](https://github.com/libretro/bnes-libretro/pull/12), looks like that was the only one.

Test-Build started: http://jenkins.kodi.tv/job/LINUX-64/

**Comment by garbear** [comment]
looks like libCEC failed because [git-rev.sh](https://github.com/Pulse-Eight/libcec/blob/master/src/libcec/cmake/git-rev.sh) echoed an error message with a newline

**Comment by fetzerch** [comment]
I forgot to untick the CMAKE_ROOT checkbox. New build http://jenkins.kodi.tv/job/LINUX-64/9912

**Comment by fetzerch** [comment]
Closing, https://github.com/fetzerch/kodi-game-scripting/commit/7ddf037a4c1f3613dfeef2074dbea92ead588105. Will push updates to games in a moment.
