### ISSUE TITLE
Add GitHub Issue template to all addons

### ISSUE THREAD

**Issue by fetzerch** [fetzerch/kodi-game-scripting#37]
https://blog.github.com/2016-02-17-issue-and-pull-request-templates/

@garbear / @MartijnKaijser I guess it would be easiest if you create the template, I can add it and roll it out here.

**Comment by MartijnKaijser** [comment]
See https://github.com/xbmc/xbmc/tree/master/.github
It should be a good start unless you want to add more
Note that ISSUE_TEMPLATE.md and bug_report.md in the subfolder are exactly the same because of github being stupid on mobile layouts.
