### ISSUE TITLE
Tag versions

### ISSUE THREAD

**Issue by fetzerch** [fetzerch/kodi-game-scripting#38]
Kodi's Jenkins will build and upload the addons only if they have a tagged version.
Tagging scheme: `1.1.0-Leia`. See https://github.com/kodi-game/game.libretro.2048/releases

**Comment by garbear** [comment]
We'll need to do something similar to LE (add a sub version) because the current versions refer to the upstream version

**Comment by fetzerch** [comment]
Some questions:
- [ ] When should the tagging happen? Every time we push an update to all addons?
- [ ] Should we refer to exact upstream versions (instead of [master](https://github.com/kodi-game/game.libretro.2048/blob/master/depends/common/2048/2048.txt)) to allow for reproducible builds?
  - Currently depending on when you build the addon, you get a different version of the libretro core pulled.
  - This can lead to a situation where the kodi addon data (`settings.xml`) doesn't match to the core.
- [ ] Versioning for the tag: Should we use v1.0.4_XX-Leia (XX would be increased every time we push an update). If we have the exact version in `addon.txt` we can then also find out which exact upstream version a specific version of our addon is referring to.

**Comment by MartijnKaijser** [comment]
You can use whatever tag you want as that is only a trigger for jenkins to start the upload to repo part. The version use will be taken from the addon.xml it self.
At some point the Jenkinsfile need to be update with specifying what branch is what version once Leia and M** will start to diverge and you need to have different builds uploaded.
https://github.com/xbmc/pipeline-library/blob/master/vars/buildPlugin.groovy#L27-L30

imo tagging should happen when you know it should be shipped to users.

Having the builds matching the correct libretro core should be preferable.
