### ISSUE TITLE
Add parallel-n64 to the scripts

### ISSUE THREAD

**Issue by jack77er** [fetzerch/kodi-game-scripting#52]
Would it be possible to integrate the libretro-parallel-n64 core from https://github.com/libretro/parallel-n64?
Thank you!

**Comment by fetzerch** [comment]
Does that core work without opengl rendering support (which kodi doesn't support at this point in time).

**Comment by jack77er** [comment]
As written [here](https://www.libretro.com/index.php/parallel-n64-with-multithreaded-angrylion-released/) it  should. It could use a Vulkan API or an own renderer (Angrylion). Correct me if I'm wrong.

**Comment by jack77er** [comment]
I've tried but nothing was build. Output:

> Fetching libretro-super repo
> Existing repo libretro-super
> Fetching libretro-super
> Resetting libretro-super
> Cleaning local changes libretro-super
> New repo, creating game.libretro.parallel_n64
> Processing the following addons: parallel_n64
> First iteration: Generate Makefiles
>  Processing addon: game.libretro.parallel_n64
>   Generating README.md
>   Generating .gitignore
>   Generating Jenkinsfile
>   Generating CMakeLists.txt
>   Generating .travis.yml
>   Generating appveyor.yml
>      Copying .github/ISSUE_TEMPLATE.md
>      Copying .github/ISSUE_TEMPLATE/bug_report.md
>   Generating depends/common/parallel_n64/windows-deps.txt
>   Generating depends/common/parallel_n64/parallel_n64.txt
>   Generating depends/common/parallel_n64/CMakeLists.txt
>   Generating depends/windows/mingw/mingw.txt
>   Generating depends/windows/mingw/mingw.sha256
>   Generating depends/windows/mingw/01-make.bat.in.patch
>   Generating depends/windows/mingw/CMakeLists.txt
>   Generating depends/windows/mingw/02-MinGWConfig.cmake.in.patch
>   Generating game.libretro.parallel_n64/addon.xml.in
>   Generating game.libretro.parallel_n64/resources/settings.xml
>   Generating game.libretro.parallel_n64/resources/language/English/strings.po
>  Processing addon description: game.libretro.parallel_n64
>      Copying platforms.txt
>   Generating game.libretro.parallel_n64.txt
> Second iteration: Generate Metadata files
>  Processing addon: game.libretro.parallel_n64
> Failed to read output library.
>   Generating README.md
>   Generating .gitignore
>   Generating Jenkinsfile
>   Generating CMakeLists.txt
>   Generating .travis.yml
>   Generating appveyor.yml
>      Copying .github/ISSUE_TEMPLATE.md
>      Copying .github/ISSUE_TEMPLATE/bug_report.md
>   Generating depends/common/parallel_n64/windows-deps.txt
>   Generating depends/common/parallel_n64/parallel_n64.txt
>   Generating depends/common/parallel_n64/CMakeLists.txt
>   Generating depends/windows/mingw/mingw.txt
>   Generating depends/windows/mingw/mingw.sha256
>   Generating depends/windows/mingw/01-make.bat.in.patch
>   Generating depends/windows/mingw/CMakeLists.txt
>   Generating depends/windows/mingw/02-MinGWConfig.cmake.in.patch
>   Generating game.libretro.parallel_n64/addon.xml.in
>   Generating game.libretro.parallel_n64/resources/settings.xml
>   Generating game.libretro.parallel_n64/resources/language/English/strings.po
> Generating summary
>   Generating wiki.txt
>   Generating summary.html

**Comment by fetzerch** [comment]
This script doesn't help you much if all you want is to compile the addon[1].
It's probably easier to follow the [instructions](https://github.com/xbmc/xbmc/tree/master/cmake#building-binary-addons), or use the [scripts](https://forum.kodi.tv/showthread.php?tid=337490).

[1] What it does is: first create the bare minimum to compile the core (`--compile`), and then read out data of the compiled library (such as version, settings and supported file extensions). All of that information is put into the .xml files that Kodi understands. If you want a working addon, then you would have to build it a second time so that these .xml are properly packaged and can be installed.

**Comment by fetzerch** [comment]
It should soon become available in the addon repo
